---
- name: Instalar Zabbix completo com suporte SNMP no Ubuntu 24.04
  hosts: coloque_seu_inventario  # ⚠️ ATENÇÃO: Substitua ou use -i para definir um inventário com este grupo
  become: true
  roles:
    - role: josezipf.zabbix7-mysql-ubuntu2404
    - role: josezipf.zabbix7-server-ubuntu2404
    - role: josezipf.zabbix7_frontend_ubuntu2404
    - role: josezipf.zabbix_agent2_v7_snmp
