---
collections:
  - name: zabbix.zabbix
    version: "1.4.1"
  - name: ansible.windows
    version: "2.8.0"
  - name: chocolatey.chocolatey
    version: "1.3.0"
  - name: community.windows
    version: "2.3.0"
  - name: community.zabbix
    version: "3.3.0"
