---
- name: Instalar ifconfig e htop (método universal)
  hosts: all
  become: yes

  tasks:
    - name: Instalar pacotes net-tools (ifconfig) e htop
      ansible.builtin.package:
        name:
          - net-tools  # fornece o ifconfig
          - htop
        state: present
